---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/kustomize.toolkit.fluxcd.io/kustomization_v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: kubernetes-replicator
  labels:
    flux.linderis.dev/skip-cluster-apps: "true"
spec:
  interval: 1h
  path: ./kubernetes/apps/kubernetes-replicator/kubernetes-replicator/app
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  targetNamespace: kubernetes-replicator
  wait: true
  timeout: 10m
