all:
  hosts:
    dokploy:
      ansible_host: 10.25.30.31
      ansible_user: ansible
      fqdn: dokploy.linderis.fr
      vm_id: 1003
      ip_cidr: dhcp
    pterodactyl:
      ansible_host: 10.25.30.2
      ansible_user: ansible
      fqdn: pterodactyl.linderis.fr
      vm_id: 1002
      ip_cidr: dhcp
    tailscale-gw:
      ansible_host: 10.25.30.2
      ansible_user: ansible
      fqdn: tailscale-gw.linderis.fr
      vm_id: 1000
      ip_cidr: dhcp
  children:
    terraform:
      hosts:
        dokploy: {}
        pterodactyl: {}
        tailscale-gw: {}
