---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/cert-manager.io/certificate_v1.json
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: linderis-fr
spec:
  secretName: linderis-fr-tls
  issuerRef:
    name: letsencrypt-production
    kind: ClusterIssuer
  commonName: linderis.fr
  dnsNames:
    - linderis.fr
    - "*.linderis.fr"
