---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/kustomize.toolkit.fluxcd.io/kustomization_v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: headscale-subnet-router
  labels:
    flux.linderis.prod/sops-secret: "true"
spec:
  interval: 1h
  path: ./kubernetes/apps/headscale/subnet-router/app
  prune: true
  dependsOn:
    - name: headscale
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  targetNamespace: headscale
