# Générer les valeurs puis chiffrer :
#   secret-key     : openssl rand -base64 60 | tr -d '\n'
#   postgresql-password : openssl rand -base64 32 | tr -d '\n'
# Puis : sops --encrypt --in-place secret.sops.yaml
apiVersion: v1
kind: Secret
metadata:
  name: authentik-credentials
type: Opaque
stringData:
  secret-key: ENC[AES256_GCM,data:BvJSMvMK6q44z0a4VAsI2Lc1okkCVUEcMmv1D4dNkJVgX0u8F4QHjDRSWklwMQf6+Zj4AVhliqUSLbGNaxvivExnYqb3e2faxUNJBukAu2M=,iv:0EvU0+UOFt5kKHXPfu9bkAMolFlO/2wScLQjML1I7W8=,tag:kOOOHkGSeGYW4YzCrmMEgg==,type:str]
  postgresql-password: ENC[AES256_GCM,data:lgAT9epbl9il3qvgNKqg2XwbB0u6/krqYoAFxhOVJclKTf8VaSww5sc89E8=,iv:ADvINyTVbyhIOJgfc/WUHGwMrTFFyRn6py1bGefVetc=,tag:KZRn1at40p0xREVeP2smDw==,type:str]
sops:
  age:
    - recipient: age1sdspueq7sx87ahpu2aqsg5xfypn0qmnadt67qpatahja8e7gap6qw55hq4
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBKK2ZDTmljdWhTN2h0ZTVY
        Uk9CWFVIWitNRUd1VlFCQlZ5bUt1Q0xvQ2djCjhMKzU1MW5JUXgyWTIrWllGV2ZN
        UkQySTU0bkY1VEI1QldIeW1ERkhhRlEKLS0tIGJPQWtXY1RvdlN4ZzlxT0tPc3Jv
        MFp4VDNZMXkydFFwVkRoMW9jcTVzZFkKtddD1C5VSryVB6IxER15DShox+xZT5xH
        4GaEkqWJFcQoJdlb4FI7EiUBg9GJKMmG1jERPtndtBcLg6pYgQ1rnw==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-02-22T18:01:34Z"
  mac: ENC[AES256_GCM,data:jeyoaH8JMCv9Pb9VYTE0EE5ORW8SlRJrp99J+NJK6ZlUu3Zo6PmIGJ5askePDrah2PG0knZcT9mV/ft6wkpJUyNRE8LX8GO0nYduqMU6J7Mt+jgwCOoPmhI3+JJAnrbrb7VaFqyf6zlVIWB0QRmoPqV3ynDm4FCNwVvATgcnaj8=,iv:tu2Dma0RwBLJnRnS9w+O5b4Clgkn280xlcutwYAEklo=,tag:MDgzF6lVbs6UHqFPQOS8QA==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
