---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/helm.toolkit.fluxcd.io/helmrelease_v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: vaultwarden-kubernetes-secrets
spec:
  chartRef:
    kind: OCIRepository
    name: vaultwarden-kubernetes-secrets
  interval: 1h
  values:
    env:
      config:
        VAULTWARDEN__ORGANIZATIONID: "60fc758e-fd71-414d-b6bf-128f0a66f793"
        VAULTWARDEN__COLLECTIONID: "42bfa535-afeb-4e57-bee7-56a9c4174558"
        VAULTWARDEN__SERVERURL: "https://vaultwarden.linderis.fr"
    image:
      tag: "1.2.8"
    namespace:
      create: false
      name: vaultwarden
