---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/helm.toolkit.fluxcd.io/helmrelease_v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: vaultwarden-kubernetes-secrets
spec:
  chartRef:
    kind: OCIRepository
    name: vaultwarden-kubernetes-secrets
  interval: 1h
  values:
    env:
      config:
        VAULTWARDEN__ORGANIZATIONID: "LINDERIS"
        VAULTWARDEN__COLLECTIONID: "HOMELAB-K8S-SYNC"
        VAULTWARDEN__SERVERURL: "http://vaultwarden.vaultwarden.svc.cluster.local"
    image:
      tag: "1.2.8"
    namespace:
      create: false
      name: vaultwarden
