apiVersion: v1
kind: Secret
metadata:
  name: vaultwarden-kubernetes-secrets
  namespace: vaultwarden
type: Opaque
stringData:
  BW_CLIENTID: ENC[AES256_GCM,data:/wyz83RQasGwCGxWHJH7MmMlJOICOCc+QP6tzBI2F79LBdfvuhrpAZM=,iv:eS79+/GE99Rhdi1zB+eqdkiWwKLwLuS8BzXc5nhycFM=,tag:6r2Xmd+GOcgZLaegtFnomA==,type:str]
  BW_CLIENTSECRET: ENC[AES256_GCM,data:KFwMMAFx9jseKjOjbCEkxQh5oG9VS/0LpnGKcnz8,iv:bCLzEbUPe2KxgwWJYmR+17G1pj0ajTNVqj5K5fYn1eM=,tag:YCATefnkP6vPpw6E2lpcBQ==,type:str]
  VAULTWARDEN__MASTERPASSWORD: ENC[AES256_GCM,data:KGlrcQymxNNVyUFvmnUZpkImRvapDCSPnA==,iv:EsrRACcaij/T696iH+GFOtJrxjnbqVTXBW9HCuPD1n0=,tag:o8pljqAOJsAugWVxuGanWw==,type:str]
sops:
  age:
    - recipient: age1sdspueq7sx87ahpu2aqsg5xfypn0qmnadt67qpatahja8e7gap6qw55hq4
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBRdkEyaFRhRVJPZ3BTcWpR
        bnk5NTdBK09TeDczbzYzbE9rV2RHZ0NpMFZVCi85TGVqWmJIMmNWcUo0cU1xakFY
        UDAxTVgybmtpNmdHNU5Bem5ucjMyamsKLS0tIGpGYi9acURDekNNVDEzaWFieDRp
        R25MMUQzVFpQVjlHdk1IYjY3bkJ0QmMKBIQ12W7DgFwJE8mGOkL7e7Ana1reGvzq
        LRUfVA4fwCypeA6jb0VeWe8jKcPsKVtJScZI71FFiD7rEZcYAP2C0A==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-02-18T17:25:25Z"
  mac: ENC[AES256_GCM,data:FZNgPXkXoko6dNYZTg0OUhHzjnT8rQ9ZgFWRIinZbiOcI1GtIPGUVPApNLpkTxZ4quHd3+Xe9sZFmxveWHXBzvGX0JcAGT13awnxfs4XFa9714DrsoripNWD2GXs9Z9Ggh+YjfOZ5Z/3IhBNPxt8l/6bhnlUpajTRBSRIx0i17c=,iv:jqx7Byh21Wd2B7NPEziWFzbjfYMQ7tJF/5K47Ohp9DQ=,tag:rQA7rsmcQxQToqNmf3wPgA==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
