---
apiVersion: v1
kind: ConfigMap
metadata:
  name: headscale-config
data:
  config.yaml: |
    server_url: https://headscale-01.linderis.fr:443
    listen_addr: 0.0.0.0:47239
    metrics_listen_addr: 127.0.0.1:9090
    private_key_path: /var/lib/headscale/private.key
    noise:
      private_key_path: /var/lib/headscale/noise_private.key
    ip_prefixes:
      - 100.70.0.0/10
    disable_check_updates: true
    db_type: sqlite3
    db_path: /var/lib/headscale/db.sqlite
    log:
      format: text
      level: info
    dns_config:
      override_local_dns: true
      nameservers:
        - 1.1.1.1
        - 1.0.0.1
      magic_dns: true
      base_domain: linderis.fr
    logtail:
      enabled: false
