---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./pvc.yaml
  - ./headplane-configmap.yaml
  - ./headscale-configmap.yaml
  - ./deployment.yaml
#  - ./headplane-secret.yaml this secret was created by vaultwarden sync
  - ./service.yaml
  - ./httproute.yaml
