apiVersion: v1
kind: Secret
metadata:
  name: test
  namespace: default
type: Opaque
stringData:
  CLOUDFLARE_DNS_TOKEN: ENC[AES256_GCM,data:PioOsoxYF+lnuInNYRR6/Gy8OsrmcjDO4ILEcG81g2tjR38qJZNRNw==,iv:RwbUEh0PTjytLBUgdjHFu6KbONSqHuDqPmSwPJvN0Uo=,tag:qVNwXrkx6S3XGE1cticb7A==,type:str]
sops:
  age:
    - recipient: age1sdspueq7sx87ahpu2aqsg5xfypn0qmnadt67qpatahja8e7gap6qw55hq4
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBPdGc0Y2ZxU1RieEFXV1Iv
        WkxZTHVkZUJpdy9xbXk5b3dmZnBwLzN0OG5NCnNTeFprcWlxN1MyY213OXJTNVNm
        MjkyZ3g3eWpsM1NlQlI4VjJlaHBKM2sKLS0tIDVXK3lGRDd5cEFaVHJGKzR4V2l4
        VmdKT1hia2hFQk1yN2VPTE9uN1FqU1EK+JJjForsvoN9xl5cDSUoYC5iqk85w2Y9
        EeEFfog/NVC6Nbmbbic9xIQGpv3p+6Nn369ro04JOqUk+lPPG6214w==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-11-23T21:18:04Z"
  mac: ENC[AES256_GCM,data:1lNompeHYaYTX/SDTT8og8gg53WDNmliloWhiBdRwmlDm+1OclesxGH1x/ppvapf6+MsoQqRwms7dOguo1aLtQI6trdWcTw+jK/IsEpYREEe0p7CKjKWCMjIyb7NJvtP5ZpfhtZgi0mPvxA/987qHDnoLgZlfFKjfDDcOcOgPTE=,iv:rFbrGuT0mbcpoKkcHcfSlXejqBy73eTG3yj6FL80bsM=,tag:la3SOkUpJ6gbwfs4LlJlZw==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
