---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: subnet-router-state
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn-production-v1
  resources:
    requests:
      storage: 128Mi
