apiVersion: v1
kind: Secret
metadata:
  name: external-dns-secret
type: Opaque
stringData:
  PDNS_API_KEY: ENC[AES256_GCM,data:Vx3nsC+Ht1YoMmBfSivPEgHRjwkmMPUYPe+n++/9ESOvXlHU6xbNFSY=,iv:gLuRJqXOqma8xxuQC6ZNq6HsDVLBlTy+Dt9Smj3KHos=,tag:nAEwMMSpBWZjWWQHWBvusA==,type:str]
sops:
  age:
    - recipient: age1sdspueq7sx87ahpu2aqsg5xfypn0qmnadt67qpatahja8e7gap6qw55hq4
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSArTTdrVGliOXdQU3FyOTU5
        eUdzSnJhbnF1NzRBNkt5NitJdTIxK1NQalNBClMvaWRaWUZYbFFGMk9zaXlvK2tr
        cjI3OC9zMTZPS0FsTVpudXplNGsvU1EKLS0tIGE5UkZtak9kWklVcEI2MW9MRWdV
        MnR0WXIyRXkvQldoQWhkSFBjV0JJMDQKslA2IR1PJErkK5q/5/xQ1EgOQxHWRL0O
        ftZr2Svyey2LZ93zSghGRK0TT0Q16lNElnUGcTt48b1Od8TTV6ipmw==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-02-15T19:52:12Z"
  mac: ENC[AES256_GCM,data:+NeBIidlwAUsWkVMkhSzqhPTgPF6OE7aiwMuhmrnhPm8RYqV6553exkdtzdw0/Kc5brQelbl/RWH5a/BQI7Fa2w2O2YtPeV1VSz8kELbzVntNrwepa0/DOfdUWmQ2MXO5CE/HecD/G5mWM2aBnHRvM6TFxILINcrWq7m4VPXjiU=,iv:v3Mx64DYZ8gRzsaXwCEQI7Lt3UISizf5/DxjO0fddBY=,tag:pMartO0ftDqk6U27j/n8jA==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
