all:
  hosts:
    test:
      ansible_host: 10.25.30.12
      ansible_user: ansible
      fqdn: test.linderis.fr
      vm_id: 1010
      ip_cidr: dhcp
  children:
    prod:
      hosts:
        test: {}
    terraform:
      hosts:
        test: {}
