---
# yaml-language-server: $schema=https://datreeio.github.io/CRDs-catalog/cilium.io/ciliumnetworkpolicy_v2.json
apiVersion: cilium.io/v2
kind: CiliumClusterwideNetworkPolicy
metadata:
  name: allow-envoy-gateway
spec:
  # Allow traffic INTO envoy gateway pods
  endpointSelector:
    matchLabels:
      io.kubernetes.pod.namespace: network
      gateway.envoyproxy.io/owning-gateway-name: envoy-external
  ingress:
    - fromCIDR:
        - 0.0.0.0/0
      toPorts:
        - ports:
            - port: "80"
              protocol: TCP
            - port: "443"
              protocol: TCP
---
# yaml-language-server: $schema=https://datreeio.github.io/CRDs-catalog/cilium.io/ciliumnetworkpolicy_v2.json
apiVersion: cilium.io/v2
kind: CiliumClusterwideNetworkPolicy
metadata:
  name: allow-envoy-gateway-internal
spec:
  endpointSelector:
    matchLabels:
      io.kubernetes.pod.namespace: network
      gateway.envoyproxy.io/owning-gateway-name: envoy-internal
  ingress:
    - fromCIDR:
        - 10.25.0.0/16       # temporary: all home devices
        # - 10.25.200.0/24   # future: mgmt VLAN only
      toPorts:
        - ports:
            - port: "80"
              protocol: TCP
            - port: "443"
              protocol: TCP
