---
# yaml-language-server: $schema=https://datreeio.github.io/CRDs-catalog/cilium.io/ciliumnetworkpolicy_v2.json
apiVersion: cilium.io/v2
kind: CiliumClusterwideNetworkPolicy
metadata:
  name: allow-envoy-gateway
spec:
  enableDefaultDeny:
    egress: false
    ingress: false
  endpointSelector:
    matchLabels:
      io.kubernetes.pod.namespace: network
      gateway.envoyproxy.io/owning-gateway-name: envoy-external
  ingress:
    - fromCIDR:
        - 0.0.0.0/0
      toPorts:
        - ports:
            - port: "80"
              protocol: TCP
            - port: "443"
              protocol: TCP
            - port: "10080"
              protocol: TCP
            - port: "10443"
              protocol: TCP
    # Allow intra-cluster pods (fromCIDR does not match Cilium-managed endpoints)
    - fromEndpoints:
        - {}
      toPorts:
        - ports:
            - port: "80"
              protocol: TCP
            - port: "443"
              protocol: TCP
            - port: "10080"
              protocol: TCP
            - port: "10443"
              protocol: TCP
    # Kubelet readiness probe
    - fromCIDR:
        - 10.25.30.0/24
      toPorts:
        - ports:
            - port: "19003"
              protocol: TCP
---
# yaml-language-server: $schema=https://datreeio.github.io/CRDs-catalog/cilium.io/ciliumnetworkpolicy_v2.json
# Allow envoy proxies to reach the envoy-gateway control plane (xDS/gRPC)
apiVersion: cilium.io/v2
kind: CiliumClusterwideNetworkPolicy
metadata:
  name: allow-envoy-gateway-xds
spec:
  enableDefaultDeny:
    egress: false
    ingress: false
  endpointSelector:
    matchLabels:
      io.kubernetes.pod.namespace: network
      control-plane: envoy-gateway
  ingress:
    - fromEndpoints:
        - matchLabels:
            io.kubernetes.pod.namespace: network
      toPorts:
        - ports:
            - port: "18000"
              protocol: TCP
---
# yaml-language-server: $schema=https://datreeio.github.io/CRDs-catalog/cilium.io/ciliumnetworkpolicy_v2.json
apiVersion: cilium.io/v2
kind: CiliumClusterwideNetworkPolicy
metadata:
  name: allow-envoy-gateway-internal
spec:
  enableDefaultDeny:
    egress: false
    ingress: false
  endpointSelector:
    matchLabels:
      io.kubernetes.pod.namespace: network
      gateway.envoyproxy.io/owning-gateway-name: envoy-internal
  ingress:
    - fromCIDR:
        - 10.25.0.0/16       # temporary: all home devices
        # - 10.25.200.0/24   # future: mgmt VLAN only
      toPorts:
        - ports:
            - port: "80"
              protocol: TCP
            - port: "443"
              protocol: TCP
            - port: "10080"
              protocol: TCP
            - port: "10443"
              protocol: TCP
    # Allow intra-cluster pods (fromCIDR does not match Cilium-managed endpoints)
    - fromEndpoints:
        - {}
      toPorts:
        - ports:
            - port: "80"
              protocol: TCP
            - port: "443"
              protocol: TCP
            - port: "10080"
              protocol: TCP
            - port: "10443"
              protocol: TCP
