---
# yaml-language-server: $schema=https://datreeio.github.io/CRDs-catalog/cilium.io/ciliumnetworkpolicy_v2.json
apiVersion: cilium.io/v2
kind: CiliumClusterwideNetworkPolicy
metadata:
  name: allow-flux-internal
spec:
  enableDefaultDeny:
    egress: false
    ingress: false
  endpointSelector:
    matchLabels:
      io.kubernetes.pod.namespace: flux-system
  ingress:
    - fromEndpoints:
        - matchLabels:
            io.kubernetes.pod.namespace: flux-system
  egress:
    - toEndpoints:
        - matchLabels:
            io.kubernetes.pod.namespace: flux-system
