---
# yaml-language-server: $schema=https://datreeio.github.io/CRDs-catalog/cilium.io/ciliumnetworkpolicy_v2.json
apiVersion: cilium.io/v2
kind: CiliumClusterwideNetworkPolicy
metadata:
  name: allow-lan-ingress
spec:
  enableDefaultDeny:
    egress: false
    ingress: false
  endpointSelector: {}
  ingress:
    # --- TEMPORARY: remove this block to restrict to mgmt only ---
    - fromCIDR:
        - 10.25.0.0/16
    # --- END TEMPORARY ---
    - fromCIDR:
        - 10.25.200.0/24    # mgmt VLAN (permanent)
