---
# yaml-language-server: $schema=https://datreeio.github.io/CRDs-catalog/cilium.io/ciliumnetworkpolicy_v2.json
# Envoy is a reverse proxy â€” it needs to forward traffic to backend pods
apiVersion: cilium.io/v2
kind: CiliumClusterwideNetworkPolicy
metadata:
  name: allow-envoy-egress
spec:
  enableDefaultDeny:
    egress: false
    ingress: false
  endpointSelector:
    matchLabels:
      io.kubernetes.pod.namespace: network
  egress:
    - toEndpoints:
        - {}
      toPorts:
        - ports:
            - port: "80"
              protocol: TCP
            - port: "443"
              protocol: TCP
            - port: "8080"
              protocol: TCP
            - port: "8443"
              protocol: TCP
            # headscale
            - port: "47239"
              protocol: TCP
            # longhorn
            - port: "8000"
              protocol: TCP
            # prometheus
            - port: "9090"
              protocol: TCP
            # grafana
            - port: "3000"
              protocol: TCP
            - port: "18000"
              protocol: TCP
