---
# yaml-language-server: $schema=https://datreeio.github.io/CRDs-catalog/cilium.io/ciliumnetworkpolicy_v2.json
apiVersion: cilium.io/v2
kind: CiliumClusterwideNetworkPolicy
metadata:
  name: allow-kube-api
spec:
  endpointSelector: {}
  egress:
    - toCIDR:
        - 10.25.30.48/29
      toPorts:
        - ports:
            - port: "6443"
              protocol: TCP
            - port: "7445"
              protocol: TCP
