---
# yaml-language-server: $schema=https://datreeio.github.io/CRDs-catalog/cilium.io/ciliumnetworkpolicy_v2.json
# Allow all pods to reach envoy-internal on its internal ports (10080/10443)
# Needed because Cilium socket-LB rewrites 443->10443 before egress policy is evaluated
apiVersion: cilium.io/v2
kind: CiliumClusterwideNetworkPolicy
metadata:
  name: allow-envoy-clusterip
spec:
  enableDefaultDeny:
    egress: false
    ingress: false
  endpointSelector: {}
  egress:
    - toPorts:
        - ports:
            - port: "10080"
              protocol: TCP
            - port: "10443"
              protocol: TCP
