---
# yaml-language-server: $schema=https://datreeio.github.io/CRDs-catalog/cilium.io/ciliumnetworkpolicy_v2.json
# Longhorn internal: all pods in longhorn-system can talk to each other
apiVersion: cilium.io/v2
kind: CiliumClusterwideNetworkPolicy
metadata:
  name: allow-longhorn-internal
spec:
  enableDefaultDeny:
    egress: false
    ingress: false
  endpointSelector:
    matchLabels:
      io.kubernetes.pod.namespace: longhorn-system
  ingress:
    - fromEndpoints:
        - matchLabels:
            io.kubernetes.pod.namespace: longhorn-system
  egress:
    - toEndpoints:
        - matchLabels:
            io.kubernetes.pod.namespace: longhorn-system
