---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
    - ./allow-dns.yaml
    - ./allow-kube-api.yaml
    - ./policies/allow-egress-https.yaml
    - ./policies/allow-hubble.yaml
    - ./policies/allow-prometheus-scrape.yaml
    - ./policies/allow-envoy-gateway.yaml
    - ./policies/allow-ingress-lan.yaml
#    - ./policies/default-deny.yaml
