---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
    - ./allow-dns.yaml
    - ./allow-coredns-upstream.yaml
    - ./allow-kube-api.yaml
    - ./allow-egress-https.yaml
    - ./allow-flux-internal.yaml
    - ./allow-hubble.yaml
    - ./allow-prometheus-scrape.yaml
    - ./allow-prometheus-egress.yaml
    - ./allow-envoy-gateway.yaml
    - ./allow-envoy-egress.yaml
    - ./allow-envoy-backends.yaml
    - ./allow-ingress-lan.yaml
    - ./default-deny.yaml
