---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
    - ./allow-dns.yaml
    - ./allow-coredns-upstream.yaml
    - ./allow-kube-api.yaml
    - ./allow-https-egress.yaml
    - ./allow-flux-internal.yaml
    - ./allow-hubble.yaml
    - ./allow-observability-internal.yaml
    - ./allow-prometheus-ingress.yaml
    - ./allow-prometheus-egress.yaml
    - ./allow-envoy-gateway.yaml
    - ./allow-envoy-egress.yaml
    - ./allow-envoy-backends.yaml
    - ./allow-lan-ingress.yaml
    - ./allow-longhorn-internal.yaml
    - ./allow-vaultwarden-internal.yaml
    - ./allow-envoy-clusterip.yaml
    - ./default-deny.yaml
