apiVersion: v1
kind: Secret
metadata:
  name: cloudflare-issuer-secret
type: Opaque
stringData:
  CLOUDFLARE_DNS_TOKEN: ENC[AES256_GCM,data:8EuNvCxBeH3hnVlQg4ZzMcq/x2p5KqSOu7g/bW4if1sBZDsB1CRHjQ==,iv:LJriG7bso5RB1O6ey9EQpHK9Kg+KrX4i4cFFW9zV8mY=,tag:uGdMlqd6Qf++fujNV2t8Ag==,type:str]
sops:
  age:
    - recipient: age1sdspueq7sx87ahpu2aqsg5xfypn0qmnadt67qpatahja8e7gap6qw55hq4
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAvdnZYczJOQ0QyaWJ3T3Rn
        R1ZtWklvdWlNZWt5VlpGS2o5MFpYS1M5UGpzCnZWNWZOZHg0RlpyZFVjdG1WVUFs
        L08rRVM5cWJYc1N1SU9aZUV5dFJZMkEKLS0tIG5jTXNyTEQxM1AvUTkvSVJoSk9C
        R044d2pxQmVFcTJBZlJSbngrZE4vSU0K0V8+JxgjdwqQGnlLohMe+2dmrKFVn/T4
        XN3qB8Gh1NSeDSWTqbOXp3qIoWwo7fu8HzpsortbD5e8MJp3giacaQ==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-11-23T20:24:49Z"
  mac: ENC[AES256_GCM,data:wcAt6PbtFbB+heHTL0298KeCZIo8V2eHPcBuugDaTcbhZJ4udXKvQuJMF2+kDbyRbm3D19Tks0BbxEJ9WGYneT+e6IjyFg5tvBo+FXGIe+hBjYtfBUJp/xulb/+z6/D2WvKLEPyooBdwlPGx626Elu1BaK7QXODEESiwo+Nvtco=,iv:0hlNnLaT3nKNHQp7K/f3bN/1p1r+fwS2fEU0m+Z23cY=,tag:5irOIJALJvSzZPqx3ePeGg==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
