apiVersion: v1
data:
  password: ENC[AES256_GCM,data:FuXDTKrx4bMthFLq,iv:GQkakUoJJn6nSHxB5g/1WG72gbDBuRksiUzyMjKhbec=,tag:00+BB9X2F1uUYkrwaG7DHQ==,type:str]
  user: ENC[AES256_GCM,data:9dqdusss5k8=,iv:/R1Ouaw66wnbnn9hNiFoT6qGiHjdb/tG8iIwvQrX6II=,tag:ZQ12H1Zg1Wp8ZnGQZ+PgAA==,type:str]
kind: Secret
metadata:
  name: basic-auth
  namespace: cert-manager
sops:
  age:
    - recipient: age1sdspueq7sx87ahpu2aqsg5xfypn0qmnadt67qpatahja8e7gap6qw55hq4
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA4Yk8wdVJxd0RsT1pyM1Fv
        b2V5NFNtWU0waTBYN0o0YjN3S0UwRW4vZXdzCjlaOVRFY1ltazNVOVpGaDRKV3pE
        YUZ6NlZMUG9EZ3VYOXVEaGlIKzRoU00KLS0tIEU3bUhtb2hHUFB6VTNLRDZmSElo
        Q0xUWWlpY2gyKytsOUJHbXRrUTlUTWMK1Ftrd4Add0V2aKshNsWQehe9QaRJ2ivE
        OhflVdkhCeJ+EG8sWfjq6+rYKu/MU84DVIXNUqR0iYDxm229IJJxCA==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-11-25T19:35:21Z"
  mac: ENC[AES256_GCM,data:2grQpmGC0xnNYFXPGcUE9sU5RkWJc/j+FCKL+mXnOzy+3iNrSlJYvRO7Wpl4OLinjJi3HNd5Kl1qX9EahYPvsAmTHz5jrBGmEn2e/WqXAMUBYIezUFoVlCScEENFEhoheDzMglUEpI4IdeBrQ1DsTSxSGSgncEI5xUWlPDFM/qA=,iv:AT1jW2Xk4sHvqAcnh1Eag0rUjq3ZAg/2/m1vWTD5nhc=,tag:M60e4NuD3yobvEZOtwtcnw==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
