apiVersion: v1
data:
  password: ENC[AES256_GCM,data:HvF3fexgP4/sLCKD,iv:UB7R5AsHJ++zb/+hUYAAjdETZf+tExb3btKqY8Ai8Ok=,tag:uMPL9EJTMQ0FS1aupQdpwQ==,type:str]
  user: ENC[AES256_GCM,data:3WZLvy4TXF8=,iv:3rwT+q9VIuMKFuh4nsIiujAKfjARAoYgBxCPtbRWD1Q=,tag:DsMWlP6z7Hyyg9LQL5gvxQ==,type:str]
kind: Secret
metadata:
  name: basic-auth
sops:
  age:
    - recipient: age1sdspueq7sx87ahpu2aqsg5xfypn0qmnadt67qpatahja8e7gap6qw55hq4
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBhNm5QeFgzbnJHTDdVMEJW
        VWVRSks4VllTOW5DQUJvN2ZGdC82MTQzcDBjCnFXOENtRFcrUlg5SmJkRnNMWHBD
        ZTlWWVNkYWgwWUpYSUNYZFh4VUt6QTAKLS0tIDVvOStQUkZvS29sTnJDTy9kYXNt
        YVBjbUh4b0t6OEMwbWRvVTJmZ0dwQk0KlsVRLpBphE25n7bkdH1OZrgBqrwEJfqO
        a0vHAw/g0UQ6kd2D7AHo9nBV350aQT5sdtYy0C8oL+M8bPKQ7DoROg==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-11-25T19:26:20Z"
  mac: ENC[AES256_GCM,data:m2AYnOo1U/G1TEy7I+ZhtmneuHcoCynQxL+39eb0xdR4OV8Pd+PwJ9hzqNir6OFUtpoUseZdnh+ZtyLFpxvMbnaLx0tRFratB3Nn6LMFk2axf4Fs36u/PAzYni14UAlBcVArDreUNL+BivwfhaU1ik28XmSbPK3amr8Z0ltXkSA=,iv:nKmEKbP+hsWEgOxh74teW8m69pYladcfeCCh1HA9/D0=,tag:NCkCnqDY0WXjaDmpKGZpKg==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
