apiVersion: v1
kind: Secret
metadata:
  name: cloudflare-issuer-secret
type: Opaque
stringData:
  CLOUDFLARE_DNS_TOKEN: ENC[AES256_GCM,data:GYaJYH1sKghRfWesyIY2mjjwr9F0g/PLK8gK1L8GwEqnvv7gNQH4ig==,iv:Ue174OTgmpUbxuDByxZnhHa47NMZpMcLLqi4NIR+a24=,tag:mOL2dTUN925BSVu1wco/IA==,type:str]
sops:
  age:
    - recipient: age1sdspueq7sx87ahpu2aqsg5xfypn0qmnadt67qpatahja8e7gap6qw55hq4
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBEOUg5QklDQkhWTDRhanhQ
        RFE1U0lPSzNkeDZWeEFJMjdVcU54Y3JMMkJZCjh3L2tBODlqMisrY012NWw5aTdN
        Tmk0UDZmY2l6N2ZUcEk1QWxFY1g0OTQKLS0tIEkxbmg2TVE5cW5kNHA4VytqUlJa
        Nm5MaHpaNDk4c3lFRjdYSDZuTEwwZDgK1HI4li2kF6vwjC3Fuqhj38VUoYdNRvRs
        1iO9ZdnwYh47ndzz/RTzq3MBlPRn84pysF5j+WfkXHT82auQICwy5A==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-02-15T16:06:42Z"
  mac: ENC[AES256_GCM,data:+uv5yuHdpEY19wnZSNhqLCHztBKUIQFCyOs4sUxaPPAs1ebf+LV64gUq5mmXM5Vyxm2Qxg3IKlqolq2W510zSu2LDGQwDsncR+iaqcQXohtmv3Th355qC0Yj4b2fvyyNcRGjBa6rreRqWl+zBD93vMnfKWKEe9bpYfmXXdcE5hg=,iv:J+g+RzQNHF64HYk9MbqlAyzFwKuGIlDU3L4afvQTi14=,tag:SBKzWZFFFvnydwggHHKPrw==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
