apiVersion: v1
kind: Secret
metadata:
  name: cloudflare-issuer-secret
type: Opaque
stringData:
  CLOUDFLARE_DNS_TOKEN: ENC[AES256_GCM,data:NwX6OB4YMXjx7mFo86eYzlPbe4AxAyev1WNTrqncbXwzJh31hqPn6w==,iv:BHr/fUUe/g/jpdJ6JmjR02uuhwipwkT5avLctM/23vI=,tag:Jj0yyNa6xBbJ0J713F/aEw==,type:str]
sops:
  age:
    - recipient: age1sdspueq7sx87ahpu2aqsg5xfypn0qmnadt67qpatahja8e7gap6qw55hq4
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB6dHpGbkp0ak80WHpLVkdv
        cEt0czJURmd2QW0yQnBSdFdCVy9vOHAxSmpJCjAxUDRvVnJkRUVVbi9sYnp4SUJv
        WHZXQ0ZiYnF1RXo0SXIxdEhrNDJmelUKLS0tIGtlNnlRL1l0dVVUWEE1WmYzMUdE
        dEJpdWpMYm56THRoRFRoZktEWFV5MmsKvf3DRBM7BWs02trbUek3PG0SpeysO1So
        dXptx5/yUjFg3o/WHkVAqvUL2ovzGEzrIrqbf1+AbFPrF2epc95/Qg==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-11-25T17:35:42Z"
  mac: ENC[AES256_GCM,data:3jQVUe5ywK7yri83aAuOKQdtbxJ4j9raAYT/QWYy1eBJKKHw8GGQZStS5ydw/CDFdoh6NVJKZ+H6uyyZUO8yfrUZyMeQ7w+bOvtgIG0WVs8cNmAvXRX/sfftvqWAb5YwUZzBBtmSsqpJvpKV5FuIzpnVV/7/Ask4s9uU2Zd7irs=,iv:mkHWfi8MhFLQHpWjETCbeIvLUqoZMfFd+RHPd0/TCPU=,tag:JQo3llVLsgTPp1r/4a+KmQ==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
