---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/kustomize.toolkit.fluxcd.io/kustomization_v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: vaultwarden
  labels:
    "flux.linderis.prod/skip-sops-secret": "true"
spec:
  interval: 1h
  path: ./kubernetes/apps/vaultwarden/vaultwarden/app
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  targetNamespace: vaultwarden
  wait: true
  timeout: 10m
