---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: flux-system

resources:
  - ./namespace.yaml
  - ./gitrepository.yaml
  - ./flux-operator/ks.yaml
  - ./flux-instance/ks.yaml
  - ./cluster-apps-ks.yaml
