---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - kube-system
  - observability
  - cert-manager
  - network
  - kubernetes-replicator
  - default
  - longhorn-system
  - vaultwarden
  - system-upgrade
  - headscale
