---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - kube-system
  - observability
  - cert-manager
  - network
  - ./basic-auth.sops.yaml
