apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: vaultwarden
spec:
  chart:
    spec:
      chart: vaultwarden
      version: '0.34.6'
      interval: 5h
      sourceRef:
        kind: HelmRepository
        name: vaultwarden
  releaseName: vaultwarden
  interval: 1h
  values:
    storage:
      data:
        name: "vaultwarden-data"
        size: "15Gi"
        class: "longhorn-production-v1"
        accessMode: "ReadWriteOnce"
        keepPvc: true
    adminToken:
      value: "$argon2id$v=19$m=19456,t=2,p=1$y/9ugQTyPKzAffmBPkb4iA$nCKLG6CfCiWF9VCvn6XSC1eW5+J1vPoxznwYiqEZKaM"
    replicas: 1
    domain: "https://vaultwarden.linderis.fr/"
    ingress:
      enabled: true
      hostname: vaultwarden.linderis.fr
    metrics:
      serviceMonitor:
        enabled: true
    timeZone: "Europe/Paris"
  dependsOn:
    - name: envoy-gateway
      namespace: network
