apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: vaultwarden
spec:
  chart:
    spec:
      chart: vaultwarden
      version: '1.10.1'
      interval: 5h
      sourceRef:
        kind: HelmRepository
        name: vaultwarden
  releaseName: longhorn
  interval: 1h
  values:
    storage:
      data:
        name: "vaultwarden-data"
        size: "15Gi"
        class: "longhorn-production-v1"
        keepPvc: true
    adminToken:
      value: "$argon2id$v=19$m=19456,t=2,p=1$TUEzcWlWZ0pLMTFCa1J3SnlKQ1dEWE5JaE1VamIwWFA0V1ppSkg0cWw2OD0$xHaxyrzoEiFYcQJ2i8Iu800ny7YH71L2TCpN/cgPuXg"
    replicas: 1
    domain: "https://vaultwarden.linderis.fr/"
    ingress:
      enabled: true
      hostname: vaultwarden.linderis.fr
    metrics:
      serviceMonitor:
        enabled: true
    timeZone: "Europe\Paris"
  dependsOn:
    - name: envoy-gateway
      namespace: network
